services:
  backend:
    image: ${IMAGE_TAG}
    ports:
      - 80:8000
    environment:
      OPENWEATHER_API_KEY: "${TOKEN}"
      CITY: "${CITY}"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]